// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5nRzJXJfIlgplBGjxsneyrO74S5J0AQ',
    appId: '1:910771032127:web:bdbd1cbd3bc7cb66d7288a',
    messagingSenderId: '910771032127',
    projectId: 'synctours-83f79',
    authDomain: 'synctours-83f79.firebaseapp.com',
    storageBucket: 'synctours-83f79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl-UTXvYwWbpJ_KBoMIqDeSH571btEUYg',
    appId: '1:910771032127:android:079caac3967b115bd7288a',
    messagingSenderId: '910771032127',
    projectId: 'synctours-83f79',
    storageBucket: 'synctours-83f79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZrp0dufNdtmta3fKTHZy8ibwsazACamg',
    appId: '1:910771032127:ios:051076cba639f2f3d7288a',
    messagingSenderId: '910771032127',
    projectId: 'synctours-83f79',
    storageBucket: 'synctours-83f79.appspot.com',
    iosBundleId: 'com.example.synctours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZrp0dufNdtmta3fKTHZy8ibwsazACamg',
    appId: '1:910771032127:ios:051076cba639f2f3d7288a',
    messagingSenderId: '910771032127',
    projectId: 'synctours-83f79',
    storageBucket: 'synctours-83f79.appspot.com',
    iosBundleId: 'com.example.synctours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ5nRzJXJfIlgplBGjxsneyrO74S5J0AQ',
    appId: '1:910771032127:web:b9d8571063847313d7288a',
    messagingSenderId: '910771032127',
    projectId: 'synctours-83f79',
    authDomain: 'synctours-83f79.firebaseapp.com',
    storageBucket: 'synctours-83f79.appspot.com',
  );
}
